name: humidity-sensor-sense-hat
version: 0.1 
summary: Humidity Sensor for the RPi2 Sense Hat
description: Humidity Sensor for the RPi2 Sense Hat reading the data from the sensor and displaying the info on the LED.
confinement: devmode 
icon: Humidity_Sensor_Icon.png

#source: https://github.com/pedrococa/humidity-sensor-tag.git

apps:
  humidity-read:
    command: bin/humidity-read

parts:
  sense-hat: 
    plugin: python3
    source: http://github.com/RPi-Distro/python-sense-hat
    source-type: git
    build-packages: [libjpeg-dev, zlib1g-dev]
    stage-packages: [python3]
  humidity-read: 
    plugin: copy
    files:
      humidity.py: bin/humidity-read
